---
- name: Add config file to a server
  become: yes
  hosts: 192.168.1.102
  roles:
    - roles/sari.nagios-server


- name: Configure nagios client
  hosts: 192.168.1.103
  become: yes
  roles:
    - sari.nagios-client
